package.json
When I running  `$ npm run dev` command, it comes up with following error message on home page.
```
Error in ./withStyles
Module not found: Error: Can't resolve '@babel/runtime/core-js/map' in '/Users/than/Source/BiiLabs/TangleID/node_modules/material-ui/styles'
ModuleNotFoundError: Module not found: Error: Can't resolve '@babel/runtime/core-js/map' in '/Users/than/Source/BiiLabs/TangleID/node_modules/material-ui/styles'
at factoryCallback (/Users/than/Source/BiiLabs/TangleID/node_modules/next/node_modules/webpack/lib/Compilation.js:269:40)
at factory (/Users/than/Source/BiiLabs/TangleID/node_modules/next/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
at resolver (/Users/than/Source/BiiLabs/TangleID/node_modules/next/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
at …
```
=> Fix `@babel/runtime` not found in `material-ui`

components/Loader/index.js, components/LoginDialog/index.js, components/NewUserForm/index.js, components/SimpleForm/index.js, components/material/Nav.js, components/material/PersistentDrawer.js, package.json, pages/users/new.js
Releated #5 
I upgrade the `material-ui` to latest version v1.0.0, so we don't need to install the `@babel/runtime` in our dpendencies.
Something you should remind: 
- The latest version `material-ui` namespace is changed:
-  Use `@material-ui/core` instead of `material-ui`.
-  Use `@material-ui/icons` instead of `material-ui-icons` 
🚀 🚀 🚀
=> Upgrade "material-ui" to v1.0.0

package.json
The pm2 is a production managment tool.
We should focus on developing the TangleID so remove the pm2.
And it should be added in our production environment.
=> Remove pm2 from development workflow 

.eslintrc.js, STYLE-GUIDE.md, package.json
By using the Airbnb config, ESLint will check coding style and React.js component by [Airbnb JavaScript Style Guide](https://github.com/airbnb/javascript).
After this change, we should use 2-space for indent and place the semicolon before the line break.
=> Apply the Airbnb config for ESLint

reducers/users.js
Related #32 
Because giving the wrong default value empty object to the "localList",
the "checkTangleUsers" function is trying to use "localList" as an array.
By giving the correct default value [] to "localList", the problem should
be fixed.
=> Fix failed to show user list page

package.json
Heroku is a service to host the user application.
Since we no longer use the Heroku, so we remove the script for Heroku.
=> Remove Heroku script

components/ClaimList.js
Since the link reference to the wrong URL, the server cannot preload the
page on the server-side when the link is clicked, causing the server
crashed.
By setting the link correctly, fix the problem.
=> Correct link reference

utils/tools.js
Since the 'verify' and 'verifyHash' functions are not used, so we clean
up these functions. Close #48
=> Drop unused exported functions

.eslintrc.js, STYLE-GUIDE.md
Because the unary ++ and -- operators are subject to automatic
semicolon insertion(ASI), differences in white space can change the
semantics of source code.
Since we are using semicolons instead of ASI, it should be okay to use
these operators without any side effect.
By disabling the "no-plusplus" rule to use the unary ++ and --
operators.
=> Allow using unary ++ and -- operators

README.md, next.config.js, server.js, utils/iotaSetup.js
Since we are using the 'BACKEND' identifier in the IOTA library API
and the 'TangleidAPI' for the different purpose.
To eliminate misleading environment variable, separate it into two
identifiers and clarified as follows:
* IRI_HOST: an address (IP or domain) to the IRI node.
* SWARM_HOST: an address (IP or domain) to the swarm node that
implement the TangleID API.
=> Canonicalize environment variable identifier

utils/tools.js
Shadowing the variable cause confusion while reading the code.
To eliminating shadow variables, we rename the function name and
parameter name, the following function names have been changed:
* keypair -> generateKeyPair
* uuid -> generateUuid
The function name should be started with verb to express what action
it performs.
=> Avoid shadowing variables

utils/tools.js
Assignment to variables declared as function parameters can be
misleading and lead confusing behavior.
To eliminating this problem, use assignment to the new local variables
instead of function parameters.
The parameter name should be named clearly otherwise it could
be misleading, so we rename them properly.
=> Avoid reassignment of function parameters

pages/users/new.js, utils/createKeyPair.js, utils/tools.js
To increase the code readability, remove the variables that are
used as shortcuts.
=> Remove shortcut variables

packages/did/package-lock.json, packages/did/package.json, packages/did/test/did.test.js
In order to test the MAM without interaction with the real iota node,
we use the mam.tools.js to mock the MAM client, but mocking mam client
was failed.
To fix this problem, set the virtual option and add the mam.client.js
into package dependencies.
=> Fix mam client not mocked

packages/did/src/mnid.js
Since Buffer() is deprecated due to security and usability issues,
use Buffer.from() method instead.
=> Migrate deprecated buffer function

packages/did/src/index.js, packages/did/test/did.test.js
To make the API documentation reflect the module usage, remove
the unnecessary variable "DIDUtils".
=> Fix module usage not correspond to documentation

package-lock.json, package.json, packages/did/.babelrc, packages/did/package-lock.json
Since the GitHub found security vulnerabilities in packages/did, we
should also check the vulnerabilities in each "packages/*".
To avoid this problem occurred again, add command "npm run audit" to
check vulnerabilities, and fix security vulnerabilities by "npm audit
fix --force".
The "interopRequireDefault" helper is moved in new version, so add the
"@babel/runtime" into the package dependencies.
See also: https://github.com/meteor/meteor/issues/10128
=> Fix package dependencies vulnerabilities

packages/did/README.md, packages/did/README.template, packages/did/src/IdenityRegistry.js, packages/did/src/register.js
To eliminate duplicate network identifier description, move the
network identifier description to the README.
=> Add  network identifier description

packages/did/README.md, packages/did/README.template, packages/did/test/did.test.js
Since the nodes of devnet are less, it is preferred to use the mainnet
instead.
Modify the sample code and test case to register identity to the
mainnet.
=> Migrate to tangle mainnet

packages/did/README.md, packages/did/README.template, packages/did/src/register.js, packages/did/test/did.test.js
To refactor the register function, the following changes are applied:
- Pass the object parameter as register option
- Generate the seed if not provided
- Use the mainnet if not specified the network identifier
Because register function is changed, modify the document as well.
=> Refactor register function

packages/did/test/did.test.js
By default, the "mam.tools.js" log each operation to the console,
set the silent mode to disable the logging.
=> Disable logging when running test cases

packages/did/README.md, packages/did/README.template, packages/did/package-lock.json, packages/did/package.json, packages/did/src/IdenityRegistry.js, packages/did/src/did.js, packages/did/src/register.js, packages/did/test/did.test.js, packages/did/test/utils.js
It is crucial to describe the public keys on the DID document, these
public keys will be used to digital signatures, encryption and
cryptographic operations, so modify the register to describe the
public keys on the DID document.
See also: https://w3c-ccg.github.io/did-spec/#public-keys
=> Register DID document with public keys

packages/did/src/mnid.js, packages/did/test/mnid.test.js
To improve the code readability, rename the MNID module function with
meaningful names, and add code documentation.
The function name are renamed as following:
- checksum() -> generateChecksum()
- encode() -> encodeToMnid()
- decode() -> decodeFromMnid()
- encodeToDid() -> encodeToDid()
- decodeFromDid() -> decodeFrom()
=> Rename MNID module functions

packages/did/README.md, packages/did/README.template, packages/did/src/index.js
To allow using specified the IRI nodes, export the "IdentityRegistry"
class and update the quick start guide.
=> Allow specified nodes with register and resolver

package-lock.json, package.json, packages/did/package-lock.json, packages/did/package.json
The "@babel/runtime" contains some helper code and it is used for
saving the compiled code size.
Since the "@babel/runtime" is a production dependency, it should be
used in the "dependency" section in "package.json".
See also: https://babeljs.io/docs/en/babel-plugin-transform-runtime
=> Fix missing babel-runtime in runtime

packages/did/package-lock.json, packages/did/src/IdenityRegistry.js
Since the getChannelRoots() function doesn't have parameter to
specified the Tangle, it causes the IdentityRegistry cannot get
correct channel roots from Tangle and failed to get the DID document.
To fix this problem, add the additional parameter to specify Tangle.
=> Fix get incorrect channel roots

packages/did/.travis.yml
Since the project already have the TravisCI configuration in the root
directory, remove the redundant configuration file in the packages
directory.
=> Remove redundant TravisCI configuration

package.json, yarn.lock
Since the ts-jest v23.10.5 has not been tested with Jest version
v24.5.0, it will show the warning message when running the test cases.
To eliminate this problem, upgrade the ts-jest to the latest version
v24.0.2.
=> Upgrade ts-jest to version v24.0.2

package.json
Building the TypsScript package will generate the "lib" and "typings"
directory, the script should clean the "typings" directory as well.
=> Clean generated type definition directory

package.json
Because running the test case in each package is slow, modify the test
script to use the Jest directly to speed up the testing.
=> Modify test script to use Jest directly

.travis.yml, packages/jsonld/README.md, packages/jsonld/package.json, packages/jsonld/src/index.ts, packages/jsonld/src/signature.ts, packages/jsonld/tests/mock/documentLoader.ts, packages/jsonld/tests/signature.test.ts, packages/types.ts, yarn.lock
To signing the credential and verifying the signature, the following
utilities are added:
- generateRsaKeyPair
- signRsaSignature
- verifyRsaSignature
Since the "jsonld-signatures" uses the "sodium-native" package, and
"sodium-native" native codes cannot build with the latest stable
Node.js on the Travis CI, so modify Travis CI configuration file
".travis.yml" to use the latest LTS Node.js instead.
See also:
 - https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
 - https://github.com/sodium-friends/sodium-native/issues/95
=> Add utilities for JSON-LD signatures

packages/did/README.md, packages/did/src/IdenityRegistry.ts, packages/did/src/did.ts, packages/did/src/resolver.ts
To fix code documentation exceeds maximum line length of 120, add the
line break to code documentation and regenerate the README document.
=> Fix exceeds maximum line length

package.json
The Travis CI doesn't stop when lint failed, because of lint script
uses the "--force" parameter that will always return exit code 0.
To resolve this problem, remove the "--force" parameter from the lint
script.
See also: https://palantir.github.io/tslint/usage/cli/
=> Fix Travis CI doesn't stop when lint failed

packages/core/LICENSE, packages/core/README.md, packages/core/README.template, packages/core/package.json, packages/core/src/composeAPI.ts, packages/core/src/createRegisterIdentity.ts, packages/core/src/createResolveIdentity.ts, packages/core/src/createSignRsaSignature.ts, packages/core/src/createVerifyRsaSignature.ts, packages/core/src/index.ts, packages/core/src/jsonld/documentLoader.ts, packages/core/tsconfig.json
Because TangleId has many packages, it's hard for people to use
TangleID library at first sight.
To make TangleID library easy to use, add the "@tangleid/core" package
as the mainly packages and provide the core functionality:
- registerIdentity
- resolveIdentity
- signRsaSignature
- verifyRsaSignature
=> Add @tangleid/core package (#128)

packages/credential/src/credential.ts
The "generateCredential()" should not append the alias to the context
when no alias provided.
=> Fix append empty alias to context

packages/did/src/IdenityRegistry.ts, packages/did/src/did.ts
Since the "generatePublicKeys()" is generating the public key metadata
array, rename it into "createMetaPublicKeys()".
=> Rename generatePublicKeys to createMetaPublicKeys

.travis.yml, package.json
To track the code coverage to the Travis CI, add test script to show the
code coverage and individual test results, and use it on the Travis CI
configuration.
See also:
- https://jestjs.io/docs/en/cli#verbose
- https://jestjs.io/docs/en/cli#coverage
=> Track code coverage to Travis CI

README.md, packages/core/README.md, packages/core/README.template, packages/core/src/composeAPI.ts, packages/core/src/createRegisterIdentifier.ts, packages/core/src/createResolveIdentifier.ts, packages/did/README.md, packages/did/README.template
To use the words more precisely, replace "identity" with "identifier"
in each code documentation and rename the following core API names:
- registerIdentity() -> registerIdentifier()
- resolveIdentity() -> resolveIdentifier()
=> Rename core API names

did-method-spec.md
To register the DID method registry list, add the specification to
describe how to operation the identifiers with the Tangle.
See also: https://w3c-ccg.github.io/did-method-registry
=> Add DID method specification

packages/jsonld/package.json, yarn.lock
The @protected keyword is used for preventing further contexts from
overriding this term definition.
The latest version of jsonld and jsonld-signatures support @proected
keyword, so upgrade them to the latest version.
- jsonld 1.6.0 -> 1.6.2
- jsonld-signatures 4.1.1 -> 4.2.0
See also: https://www.w3.org/TR/json-ld11/#protected-term-definitions
=> Upgrade jsonld and jsonld-signatures packages

packages/jsonld/src/jsonld.ts
flatten(): collects all properties of a node in a single JSON object.
frame(): query and force a specific tree layout to a JSON-LD document.
See also:
- https://json-ld.org/spec/latest/json-ld/#flattened-document-form
- https://json-ld.org/spec/latest/json-ld-framing/#introduction
=> feat(jsonld): Add flatten and frame utilities

packages/core/src/jsonld/documentLoader.ts, packages/did/src/did.ts, packages/jsonld/test/signature.test.ts
Because TangleID DID method name is renamed into "tangle" in the
specification, change the implementation to use the same method name.
=> refactor(core): Rename DID method name

packages/jsonld/src/jsonld.ts
flatten() and frame() function return object instead of string.
=> fix(jsonld): Fix incorrect return type

packages/core/src/composeAPI.ts, packages/core/src/jsonld/documentLoader.ts
The function-based document loader makes us hard to manipulate
cached documents, so convert it to the class.
=> refactor(core): Refactor document loader

packages/jsonld/README.md, packages/jsonld/src/jsonld.ts
The DID public key information may be embedded in the DID document,
so add the "findNodeById()" function to find the node in the
document.
See also: https://w3c-ccg.github.io/did-spec/#public-keys
=> feat(jsonld): Add method to find node in document

.travis.yml
To make sure the code can be built successfully, modify the Travis CI
configuration to run the build test when each code changes.
=> ci: Add build test to Travis CI

packages/core/package.json, packages/credential/package.json, packages/did/package.json, packages/jsonld/package.json
The type declaration files are generated after compiling TypeScript
packages, but "package.json" does not mention the location of
type declaration files, it will cause other TypeScript projects
will not be able to recognize our package's types.
To fix this problem, add the missing "typings" field to mention
location of type declaration files.
See also:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
=> fix(all): Fix missing type declarations

jest.config.js, packages/core/package.json, packages/core/tsconfig.release.json, packages/credential/package.json, packages/credential/tsconfig.release.json, packages/did/package.json, packages/did/tsconfig.release.json, packages/jsonld/package.json, packages/jsonld/tsconfig.release.json, packages/mnid/package.json, packages/mnid/tsconfig.release.json, tsconfig.release.json
Using the path mapping feature in the "tsconfig.json" will cause
TypeScript compiler treats these package as source files and compile
them to generate unnecessary JavaScript code.
We need the path mapping feature to run the test cases without
compiling any TypeScript source code, so split the "tsconfig.json"
for different usages.
- "tsconfig.json": developing and testing packages (w path mapping)
- "tsconfig.release.json": building the packages (w/o path mapping)
=> fix(all): Fix generate unnecessary code

package.json, packages/core/package.json, packages/credential/package.json, packages/did/package.json, packages/jsonld/package.json, packages/mnid/package.json
The document generation workflow will compile the TypeScript to
JavaScript, then read the JSDoc from the Javascript to generate the
readme documentation.
Because we changed the split the "tsconfig.json" for different
purposes, change document generation workflow to use
"tsconfig.release.json" to compile the TypeScript.
=> fix: Fix document generation workflow
