package.json

By using the "npm run eslint" command, it checks the coding style with eslint.

Add eslint command into "packages.json"

---

components/NewUserForm/index.js

Fixed #8 
The render method should be a pure function of props and state in SimpleForm.
The SimpleForm is hard to fixed and hard to used, so I remove the SimpleForm
from the NewUserForm to fix this problem.

Fix missing data in new identity request

---

.gitignore

Fix generated JSON files not ignored.

Fix generated JSON files not ignored

---

layouts/Main.js
layouts/material/Main.js

Fix layouts coding style

---

pages/claims/info.js
pages/user.js
pages/users.js
pages/users/new.js

Fix pages coding style

---

middlewares/api.js
middlewares/fetchData.js

Fix middlewares coding style

---

actions/Login.js
actions/_helper.js
actions/checkTangleUsers.js
actions/createClaim.js
actions/createIdentity.js
actions/createMamMessage.js
actions/fetchClaims.js
actions/fetchKeyPairs.js
actions/fetchMamMessages.js
actions/fetchOffTangleUserList.js
actions/fetchUserList.js
actions/index.js
actions/showClaims.js
actions/updateLocalAccount.js

Fix actions coding style

---

reducers/index.js
reducers/users.js

Fix reducers coding style

---

store/configureStore.dev.js
store/configureStore.js
store/configureStore.prod.js

Fix store coding style

---

pages/user.js
utils/formDataUtils.js

The problem is caused by "SimpleForam", so we remove it.

Fix MAM message not send

---

.eslintrc.js
pages/users.js
utils/tangleidAPI.js

By moving the API called from server-side into client-side, the user
list page should be loaded fast.

Speedup user list page loading time

---

components/ClaimList/index.js
components/MessageList.js
components/UserProfile.js
pages/user.js
server.js
utils/tangleidAPI.js

The user profile page takes long time to load each page, that was caused
by fetching too much data in the server-side with "getInitailProps"
function.
By moving API calls from "getInitialProps" into "componentDidMount",
the server will respond faster, then call API after the page is loaded.
See also #38

Shorten user profile page load time

---

utils/cert.js
utils/createKeyPair.js
utils/localStore.js
utils/mamUtils.js
utils/tools.js
utils/transformToQRCode.js

Regarding the PR #34, I split the commit into small pieces, it will be nice to be reviewed in this PR.
Since it is hard to fix the coding style at a time, I will continue to fix the coding style problems in the next  PR.

Fix coding style

---

STYLE-GUIDE.md

Give a sample to write the React component.

Append component code example into style guide

---

README.md
next.config.js
utils/cert.js
utils/iotaSetup.js
utils/mamUtils.js

Setup the IOTA object by using system-wide configuration, and move the
setup process into 'iotaSetup.js'. Close #35

Consolidate node configurations

---

utils/cert.js
utils/mamUtils.js
utils/tools.js

To eliminate the sub-function used before it declared, put the
sub-function to the front.

Reorder sub-function placement

---

utils/cert.js
utils/createKeyPair.js
utils/mamUtils.js
utils/tools.js

Apply style tweaks from ESLint to fix the following:
* Missing semicolon
* Missing whitespace
* Unused import

Apply style tweaks

---

utils/mamUtils.js

Drop unused variable and remove the redundancy query.

Drop unused variable

---

components/NewUserForm.js

Correct two names
- firstName -> first_name
- lastName -> last_name

Correct column names in input form

---

STYLE-GUIDE.md

Make a code example to describe the new-cap rule in the style guide.
The new-cap rule:
The function name starts with the upper case which means constructor,
otherwise regular function.
Follow the link to know more detail about `new-cap` rule:
- https://eslint.org/docs/rules/new-cap
- https://github.com/airbnb/javascript#naming--PascalCase

Mention new-cap rule

---

pages/users/new.js

Change NewUserPage into class-based component.

Change NewUserPage into class-based component

---

package-lock.json
package.json
packages/did/package-lock.json

Since the package dependencies have security vulnerabilities, so fix
them with "npm audit fix"

Fix package dependencies vulnerabilities

---

packages/did/test/did.test.js
packages/did/test/mnid.test.js

To make the test cases clearly, use the "describe" keyword to
describe the context and categorize the test cases, and use
the "it" to explains each test that will be performed.

Refactor test cases

---

packages/did/package-lock.json
packages/did/package.json

Because of the following reasons, we need to change to our
maintained
packages "tic.api.js" and "mam.tools.js".
- To integrate with the Travis CI, replace the "git+ssh" with the
"git+https" in "package.json", otherwise the Travis CI cannot get the
packages with "git+ssh".
- To interact with the Mainnet, set the MWM to 14, otherwise the IRI
node will reject the transactions with "Invalid Transaction Hash"
message.

Use customized packages

---

.travis.yml

To eliminate the code misbehaving, use the Travis CI to verify the
each integration with automated testing.

Automated testing with Travis CI

---

.travis.yml
package.json
packages/mnid/package.json
tslint.json
yarn.lock

To ensure the code base style consistency, use the TSLint to check
TypeScript coding style with Travis CI.

Use TSLint to check TypeScript coding style

---

packages/credential/LICENSE
packages/credential/README.md
packages/credential/README.template
packages/credential/package.json
packages/credential/src/contexts.ts
packages/credential/src/credential.ts
packages/credential/src/index.ts
packages/credential/tests/index.test.ts
packages/credential/tsconfig.json
packages/types.ts

To generate the credential object easily, add @tangleid/credential
package.
Close #88

Add @tangleid/credential package (#88)

---

packages/connect/package.json
packages/did/package.json
packages/mnid/package.json

Fix the incorrect repository URL in each packages:
- https://github.com/TangleID/TangleID

Fix incorrect repository URL

---

README.md

Since @tangleid/core provides the core functionality, it should be
mentioned in the top-level documentation.
Revise and add the following sections in top-level documentation:
- Installing the library
- Getting started

Revise top-level documentation

---

packages/jsonld/README.md
packages/jsonld/src/jsonld.ts

Update the flatten() and frame() API reference in the readme document.

docs(jdonld): Update readme API reference

---

packages/did/README.md
packages/did/src/did.ts

- isDidUrl(): checks if given URL is a DID URL.
- decodeFromDidUrl(): decode information of the DID URL.
See also: https://w3c-ccg.github.io/did-spec/#fragment

feat(did): Add DID URL utilities

---

packages/core/src/jsonld/documentLoader.ts

Since the metadata may be embedded in the JSON-LD document and
reference itself with a fragment URL, it is necessary to make the
"documentLoader" has ability to get metadata with fragment URL.
To make "documentLoader" has ability to do that, decode fragment URL
with "decodeFromDidUrl()" and find the metadata with "findNodeById".

feat(core): Add fragment URL support

---

lerna.json

Use the conventional commit message when committing the version updates
for publication.
See also:
- https://github.com/lerna/lerna#lernajson

chore: Use conventional commit message

---

packages/core/package.json
packages/credential/package.json
packages/did/package.json
packages/jsonld/package.json

To correct the package entry point, modify the value of "main" field
in the "package.json".

fix: Correct package entry point
